version: "3.8"

services:
  db:
    image: arm64v8/postgres
    container_name: database
    restart: always
    environment:
      - POSTGRES_USER=petmatch
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=petmatch
    ports:
      - '5432:5432'

  app:
    image: arm64v8/openjdk:17-jdk-slim
    container_name: application
    ports:
      - '8081:8080'
    volumes:
      - ./build/libs:/app
    working_dir: /app
    command: java -jar PetMatch-0.0.1-SNAPSHOT.jar
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/petmatch
      - SPRING_DATASOURCE_USERNAME=petmatch
      - SPRING_DATASOURCE_PASSWORD=12345
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
      - SPRING_PROFILES_ACTIVE=default
    depends_on:
      - db